%[text] 本函数负责将英文的原始信号UID翻译为中文输出到命令行窗口。
function LogString = LogTranslate(Log)
import Gbec.UID
persistent Dict
if isempty(Dict)
	Dict=dictionary(...
		UID.Signal_StartRecord,		"开始拍摄",...
		UID.Signal_LightUp,			"灯光亮",...
		UID.Signal_LightDown,		"灯光灭",...
		UID.Signal_AudioUp,			"声音响",...
		UID.Signal_AudioDown,		"声音停",...
		UID.Signal_MonitorHit,		"命中",...
		UID.Signal_MonitorMiss,		"错失",...
		UID.Signal_WaterOffered,	"给水",...
		UID.Signal_AirPuff,			"喷气",...
		UID.Signal_HitCount,		"舔",...
		UID.Signal_HFImage,			"高频图",...
		UID.Signal_LFImage,			"低频图",...
		UID.Signal_Laser,			"激光",...
		UID.Signal_TrialStart,		"回合开始",...
		UID.State_SessionAborted,	"会话已放弃",...
		UID.Signal_Image,			"图像",...
		UID.Signal_LowUp,			"低音响",...
		UID.Signal_LowDown,			"低音停",...
		UID.Signal_HighUp,			"高音响",...
		UID.Signal_HighDown,		"高音停",...
		UID.Signal_SessionPaused,	"会话暂停",...
		UID.Signal_Optogenetic,		"光遗传",...
		UID.Signal_SessionContinue,	"会话继续"...
		);
end
%必须考虑有些键有匹配有些键无匹配的情况，不能简单try-catch
KeyLogical=Dict.isKey(Log);
LogString=strings(size(Log));
LogString(KeyLogical)=Dict(Log(KeyLogical));
KeyLogical=~KeyLogical;
LogString(KeyLogical)=string(UID(Log(KeyLogical)));

%[appendix]{"version":"1.0"}
%---
