#pragma once
#include <stdint.h>
enum class UID : uint8_t {
	//Arduino提供的服务端口

	PortA_PointerSize,
	PortA_CreateProcess,
	PortA_StartModule,
	PortA_RestoreModule,
	PortA_PauseProcess,
	PortA_ContinueProcess,
	PortA_AbortProcess,
	PortA_GetInformation,
	PortA_DeleteProcess,
	PortA_AllProcesses,
	PortA_IsReady,
	PortA_RandomSeed,

	//Computer提供的服务端口

	PortC_ProcessFinished,
	PortC_Signal,
	PortC_TrialStart,
	PortC_Exception,

	Exception_Success,
	Exception_InvalidProcess,
	Exception_MethodNotSupported,
	Exception_StillRunning,
	Exception_ProcessNotRunning,
	Exception_ProcessNotPaused,
	Exception_ProcessNotIdle,
	Exception_ProcessFinished,
	Exception_BrokenRestoreArguments,
	Exception_MethodNotImplemented,
	Exception_InvalidModule,
	
	Field_After,
	Field_Do,
	Field_ID,
	Field_SubSteps,
	Field_RandomStep,
	Field_RandomDuration,
	Field_Duration,
	Field_AbortStep,
	Field_StartModule,
	Field_Modules,
	Field_Range,
	Field_Target,
	Field_Pin,
	Field_Monitor,
	Field_Content,
	Field_Message,
	Field_HighOrLow,
	Field_Cleaner,
	Field_Period,
	Field_Times,
	Field_PeriodA,
	Field_PeriodB,
	Field_ContentA,
	Field_ContentB,

	Column_SubSteps,
	Column_Repeats,
	Column_Module,

	Type_Bool,
	Type_UInt8,
	Type_UInt16,
	Type_UID,
	Type_Array,
	Type_Cell,
	Type_Struct,
	Type_Empty,
	Type_Seconds,
	Type_Milliseconds,
	Type_Infinite,
	Type_Table,
	Type_Pointer,
	Type_Map,

	State_Ready,
	State_Running,
	State_Paused,
	State_Aborted,
	State_Finished,
	State_Normal,
	State_Repeat,
	State_Restore,
	State_Idle,

	Signal_TrialStart,
	Signal_ProcessFinished,
	Signal_ProcessStarted,

	Test_BlueLed,

	Trial_Invalid,

	Duration_Random,
	Duration_Infinite,

	Module_Sequential,
	Module_RandomSequential,
	Module_Delay,
	Module_Abort,
	Module_Restart,
	Module_Randomize,
	Module_MonitorPin,
	Module_SerialMessage,
	Module_DigitalWrite,
	Module_CleanWhenAbort,
	Module_Async,
	Module_RepeatEvery,
	Module_DoubleRepeat,
	Module_Repeat,
};