#pragma once
#include <stdint.h>
enum class UID : uint8_t
{
	//Arduino提供的服务端口

	PortA_PointerSize,
	PortA_CreateProcess,
	PortA_PauseProcess,
	PortA_ContinueProcess,
	PortA_AbortProcess,
	PortA_GetInformation,
	PortA_DeleteProcess,
	Port_AllObjects,
	Port_RandomSeed,

	//Computer提供的服务端口

	PortC_ProcessFinished,
	PortC_Signal,
	PortC_TrialStart,
	PortC_ProcessStarted,

	Exception_Success,
	Exception_InvalidProcess,
	Exception_MethodNotSupported,
	Exception_StillRunning,
	Exception_ObjectNotIdle,
	Exception_ObjectNotRunning,
	Exception_ObjectNotPaused,
	Exception_ProgressObjectNotFound,
	Exception_AsyncObjectNotFound,

	Property_StepID,
	Property_Subobjects,
	Property_ObjectInfo,
	Property_RepeatTime,
	Property_SignalValue,
	Property_StarterID,
	Property_Pin,
	Property_Duration,
	Property_Reporter,
	Property_TrialID,
	Property_TrialStep,
	Property_Repeatee,
	Property_SwitchFrom,
	Property_SwitchTo,
	Property_Min,
	Property_Max,
	Property_Unconditional,
	Property_Conditional,
	Property_AsyncStep,
	Property_Steps,
	Property_Step,
	Property_Repeat,
	Property_Abortable,
	Property_WhenAbort,
	Property_BackgroundID,

	Type_Bool,
	Type_UInt8,
	Type_UInt16,
	Type_UID,
	Type_Array,
	Type_Cell,
	Type_Struct,
	Type_Empty,
	Type_Seconds,
	Type_Milliseconds,
	Type_Infinite,

	State_ObjectRunning,
	State_ObjectPaused,
	State_ObjectIdle,
	State_Normal,
	State_Repeat,
	State_Restore,

	Signal_TrialStart,
	Signal_ProcessFinished,
	Signal_ProcessStarted,

	Test_BlueLed,

	Step_DigitalWrite,
	Step_Delay,
	Step_StartMonitor,
	Step_StopMonitor,
	Step_Trial,
	Step_RepeatIfPin,
	Step_SwitchIfPin,
	Step_AppendIfPin,
	Step_SerialWrite,
	Step_Async,
	Step_Sequential,
	Step_Random,
	Step_CustomFunction,
	Step_DoWhenAborted,
	Step_StartBackgroundRepeat,

	Trial_Invalid,

	BackgroundID_Default,

	Public_BlueLed,
};