#pragma once
#include <stdint.h>
enum class UID : uint8_t
{
	Port_PointerSize,
	Port_ObjectCreate,
	Port_ObjectStart,
	Port_ObjectRestore,
	Port_ObjectRepeat,
	Port_ObjectPause,
	Port_ObjectContinue,
	Port_ObjectAbort,
	Port_ObjectGetInformation,
	Port_ObjectDestroy,
	Port_AllObjects,
	Port_RandomSeed,
	Port_TrialStart,
	Port_Signal,

	Exception_Success,
	Exception_InvalidObject,
	Exception_MethodNotSupported,
	Exception_StillRunning,
	Exception_ObjectNotIdle,
	Exception_ObjectNotRunning,
	Exception_ObjectNotPaused,
	Exception_ProgressObjectNotFound,
	Exception_AsyncObjectNotFound,

	Property_StepID,
	Property_Subobjects,
	Property_ObjectInfo,
	Property_RepeatTime,
	Property_SignalValue,
	Property_StarterID,
	Property_Pin,
	Property_Duration,
	Property_Reporter,
	Property_TrialID,
	Property_TrialStep,
	Property_Repeatee,
	Property_SwitchFrom,
	Property_SwitchTo,
	Property_Min,
	Property_Max,
	Property_Unconditional,
	Property_Conditional,
	Property_AsyncStep,
	Property_Steps,
	Property_Step,
	Property_Repeat,
	Property_Abortable,
	Property_WhenAbort,
	Property_BackgroundID,

	Type_Bool,
	Type_UInt8,
	Type_UInt16,
	Type_UID,
	Type_Array,
	Type_Cell,
	Type_Struct,
	Type_Empty,
	Type_Seconds,
	Type_Milliseconds,
	Type_Infinite,

	State_ObjectRunning,
	State_ObjectPaused,
	State_ObjectIdle,
	State_Normal,
	State_Repeat,
	State_Restore,

	Signal_TrialStart,
	Signal_ObjectFinished,
	Signal_ObjectStarted,
	Signal_ObjectRestored,

	Test_BlueLed,

	Step_DigitalWrite,
	Step_Delay,
	Step_StartMonitor,
	Step_StopMonitor,
	Step_Trial,
	Step_RepeatIfPin,
	Step_SwitchIfPin,
	Step_AppendIfPin,
	Step_SerialWrite,
	Step_Async,
	Step_Sequential,
	Step_Random,
	Step_CustomFunction,
	Step_DoWhenAborted,
	Step_StartBackgroundRepeat,

	Trial_Invalid,

	BackgroundID_Default,

	Public_BlueLed,
};